// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnalyzeArtists(arg1:string):Promise<Array<domain.ArtistSuggestion>>;

export function DetectDuplicates(arg1:string):Promise<Array<any>>;

export function ListTracks(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<domain.ListTracksResult>;

export function OpenFolderDialog():Promise<string>;

export function ScanLibrary(arg1:string):Promise<void>;
