// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeArtists(arg1) {
  return window['go']['main']['App']['AnalyzeArtists'](arg1);
}

export function AnalyzeForOrganize(arg1) {
  return window['go']['main']['App']['AnalyzeForOrganize'](arg1);
}

export function ApplyAllHighConfidence(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyAllHighConfidence'](arg1, arg2, arg3);
}

export function ApplyOrganizerSuggestion(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ApplyOrganizerSuggestion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function DetectDuplicates(arg1) {
  return window['go']['main']['App']['DetectDuplicates'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLastDebugReport() {
  return window['go']['main']['App']['GetLastDebugReport']();
}

export function ListTracks(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ListTracks'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function OpenDebugFolder() {
  return window['go']['main']['App']['OpenDebugFolder']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function PreviewFilenameTemplate(arg1, arg2) {
  return window['go']['main']['App']['PreviewFilenameTemplate'](arg1, arg2);
}

export function RenameTrack(arg1, arg2) {
  return window['go']['main']['App']['RenameTrack'](arg1, arg2);
}

export function RescanLibrary(arg1) {
  return window['go']['main']['App']['RescanLibrary'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateTrackTags(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTrackTags'](arg1, arg2, arg3, arg4, arg5, arg6);
}
