// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {update} from '../models';

export function AnalyzeArtists(arg1:string):Promise<Array<domain.ArtistSuggestion>>;

export function AnalyzeForOrganize(arg1:string):Promise<Array<domain.OrganizerSuggestion>>;

export function ApplyAllHighConfidence(arg1:string,arg2:number,arg3:string):Promise<number>;

export function ApplyOrganizerSuggestion(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string,arg8:string):Promise<string>;

export function CheckForUpdates():Promise<update.Result>;

export function DeleteTrack(arg1:number):Promise<void>;

export function DetectDuplicates(arg1:string):Promise<Array<domain.DuplicateGroup>>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<domain.AppConfig>;

export function GetLastDebugReport():Promise<string>;

export function ListTracks(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<domain.ListTracksResult>;

export function OpenDebugFolder():Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function PreviewFilenameTemplate(arg1:string,arg2:string):Promise<Array<domain.FilenamePreview>>;

export function RenameTrack(arg1:number,arg2:string):Promise<string>;

export function RescanLibrary(arg1:string):Promise<void>;

export function ScanLibrary(arg1:string):Promise<void>;

export function UpdateConfig(arg1:domain.AppConfig):Promise<void>;

export function UpdateTrackTags(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;
