// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListTracks(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ListTracks'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}
